#!/usr/bin/with-contenv bash

print_vars () {
    if [ -n "${1}" ]; then
	title=" ${1}"
    else
	title=""
    fi
    echo "Environment${title}:"
    echo "    PUID=${PUID}"
    echo "    PGID=${PGID}"
    echo "    TZ=${TZ}"
}

print_vars $0

# load env file if it exists
if [ -f "/config/env" ]; then
  source /config/env
  print_vars "$0: After sourcing /config/env"
fi

mkdir -p /config/log
chown -R abc:abc /config/log

rm -f /config/log/.logrotate.status

